
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://aolney.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /personal-jekyll-theme
baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: "UA-7398920-6"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Andrew M. Olney"
title: "{ Andrew M. Olney }"
description: "Blog and website of Andrew M. Olney. Opinions expressed are mine."
keywords: "Olney, linguistics, computation, education, tutoring"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

#background-img: "../img/intro-bg.jpg"
background-img: ""

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text #  - text: "This site is under construction"
  - text: "Conversational intelligent tutoring systems"
  - text: "Computational representations of meaning"
  - text: "Dyadic interaction and engagement"

#me-img: "/img/jetpacktocat.png"
me-img: "/img/photo.jpg"
me-proj-1: "/img/pkd.jpg"
me-proj-2: "/img/elmo.jpg"
me-proj-3: "/img/turing.jpg"
me-proj-4: "/img/anita.jpg"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "andrewolney"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/memphis1.png"
    date: "2001 - 2006"
    description: "PhD Computer Science, University of Memphis"
  - image: "/img/timeline/sussex.jpg"
    date: "1998 - 2001"
    description: "MSc Evolutionary and Adaptive Systems, University of Sussex"
  - image: "/img/timeline/ucl.png"
    date: "1995 - 1998"
    description: "BA Linguistics with Cognitive Science, University College London"

# First image of the Timeline

timeline-img: "/img/timeline/start.png"

###########
# Work    #
###########

teaching: "[Classes at the undergraduate and graduate level](/tags/teaching.html) involving cognitive science and computational modeling. Also [graduate student mentorship in grant-sponsored research.](/tags/advising.html)"
research: "[Publications](/tags/publications.html) and [projects](/tags/project-overviews.html) focussing on [task-oriented natural langugage interfaces](/tags/nlp.html) with specific focus on [conversational intelligent tutoring systems](/tags/its.html), [computational representations of meaning](/tags/semantics.html), and [dyadic interaction](/tags/discourse.html) and [engagement.](/tags/engagement.html)"
service: "[Director of the Insitute for Intelligent Systems](http://iis.memphis.edu/), [Coordinator for the Cognitive Science Graduate Certificate, and Coordinator for the Undergraduate Minor in Cognitive Science.](http://www.memphis.edu/gradcatalog/degree_planning/cas/cog_sci.php) Also [community outreach](/tags/outreach.html) and [service to the field.](/tags/service.html)"

teaching-link: "/tags/teaching.html"
research-link: "/tags/research.html"
service-link: "/tags/service.html"

###########
# Students#
###########
people:
 - pic: "/img/team/borhan.jpg"
   link: "https://umdrive.memphis.edu/bsamei/public/"
   name: Borhan Samei
   position: Ph.D. Candidate, Computer Science
   social:
     - title: google-plus
       url: "https://plus.google.com/118424456688736358978"
     - title: linkedin
       url: "http://ir.linkedin.com/pub/borhan-samei/56/738/91"
     - title: random
       url: "https://www.researchgate.net/profile/Borhan_Samei"
     - title: google
       url: "https://scholar.google.com/citations?user=PRwePVUAAAAJ&hl=en&oi=ao"
 - pic: "/img/team/rosetta.jpg"
   link: "/tags/advising.html"
   name: Former Students


recruit-message: "If you are interested in working with me, please send me an email. [Here is some general advice for students](/category/2016/01/08/student-advice.html)"

###########
# Contact #
###########

email: "aolney@memphis.edu"

##################
# Social Buttons #
##################

social:
#  - title: "facebook"
#    url: "https://facebook.com/"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/andrewolney"
#  - title: "twitter"
#    url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/aolney"
  - title: "stack-overflow"
    url: "http://stackoverflow.com/users/343550/andrew-olney"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: google
    url: "https://scholar.google.com/citations?user=uJZP6RQAAAAJ"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

fourofour-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Work: 'work'
  Blog: 'latest-post'
# Have an idea to show development as scientist (e.g. RNN during UG) but not a lot of time now
#  Timeline: 'timeline'
  Students: 'students'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
